### ISSUE TITLE
odiglet on CrashLoopBackOff with Docker Desktop on Macbook M1

### ISSUE THREAD

**Issue by lakamsani** [keyval-dev/odigos#137]
`helm install my-odigos odigos/odigos --namespace odigos-system --create-namespace` ends in the following pods installed but `odiglet` is not coming up. 

```
odiglet-gg9tw                          0/1     CrashLoopBackOff   69 (4m35s ago)   6h9m
odigos-autoscaler-6f98b9f9-86m9s       2/2     Running            13 (5h15m ago)   6h9m
odigos-instrumentor-66bd6d6f5b-ckl7q   2/2     Running            13 (5h15m ago)   6h9m
odigos-scheduler-6d694ff89f-vhlxv      2/2     Running            14 (5h15m ago)   6h9m
odigos-ui-fb4485899-mrs9p              1/1     Running            2 (5h15m ago)    6h9m
```

Docker Desktop `4.17.0 (99724).` on a M1 Macbook `MacOS Ventura 13.3.1 (22E261)`

Error via ` k logs odiglet-gg9tw -n odigos-system` is:

```
failed to try resolving symlinks in path "/var/log/pods/odigos-system_odiglet-gg9tw_3ca139e5-35f1-48d3-a748-afe2fbcf40e8/odiglet/69.log": lstat /var/log/pods/odigos-system_odiglet-gg9tw_3ca139e5-35f1-48d3-a748-afe2fbcf40e8/odiglet/69.log: no such file or directory%
```

`k version -o yaml` shows:

```
clientVersion:
  buildDate: "2022-12-08T19:58:30Z"
  compiler: gc
  gitCommit: b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d
  gitTreeState: clean
  gitVersion: v1.26.0
  goVersion: go1.19.4
  major: "1"
  minor: "26"
  platform: darwin/arm64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-11-09T13:29:58Z"
  compiler: gc
  gitCommit: 872a965c6c6526caa949f0c6ac028ef7aff3fb78
  gitTreeState: clean
  gitVersion: v1.25.4
  goVersion: go1.19.3
  major: "1"
  minor: "25"
  platform: linux/arm64
  ```
  
  thanks
